---
- hosts: all
  tasks:
  - name: install ntp
    package: name=ntp state=latest
  - name: enable and start ntp
    service: name=ntpd state=started enabled=yes
  - name: set selinux in permissive mode
    selinux: policy=targeted state=permissive
  - name: stop and disable firewalld
    service: name=firewalld state=stopped enabled=no
  - name: install docker
    package: name=docker state=latest
  - name: enable and start docker
    service: name=docker state=started enabled=yes
  - name: add yum repository for kubernetes
    yum_repository:
      name: k8s
      description: K8s YUM repo
      file: external_repos
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled: yes
      gpgcheck: no
  - name: disable swap
    command: swapoff -a
  - name: install kubelet, kubeadm and kubectl
    yum: pkg={{item}} state=latest
    with_items:
      - kubelet
      - kubeadm
      - kubectl
  - name: enabled and start kubelet
    service: name=kubelet state=started enabled=yes
  - name: configure sysctl entries
    sysctl: name={{item}} value=1 state=present sysctl_file=/etc/sysctl.d/k8s.conf
    with_items:
      - net.bridge.bridge-nf-call-ip6tables
      - net.bridge.bridge-nf-call-iptables
