apiVersion: v1
kind: Service
metadata:
  labels:
    name: redis
  name: redis
  namespace: default
  annotations:
    pod.beta.kubernetes.io/hostname: redis
spec:
  ports:
  - port: 6379
  selector:
    app: redis
